In [15]:
#we demonstrate the benefits of vectorization i.e., removing loops while doing matrix multiplication
import numpy as np
#multiplication of col vector using numpy=> VECTORIZATION
import time
tick=time.time()
x=np.random.rand(100000)
y=np.random.rand(100000)
z=np.dot(x,y)
tock=time.time()
print("Time taken: "+str((tock-tick)*1000))
print(z)

Time taken: 4.4269561767578125
25130.80576293147


In [16]:
#multiplication normally
z=0
tick=time.time()
for i in range(0,100000):
    z+=x[i]*y[i]
tock=time.time()
print("Time taken: "+str((tock-tick)*1000))
print(z)

Time taken: 58.71987342834473
25130.805762932105


# Benefits of vectorization during matrix multiplication

In [10]:
#Without using built in functions
import numpy as np
import time
x=np.random.rand(100,100)
y=np.random.rand(100,100)
z=np.zeros((100,100))
sum=0
tick=time.time()
for i in range(0,100):
    for j in range(0,100):
        sum=0
        for k in range(0,100):
            sum+= x[i][k]*y[k][j]
        z[i][j]=sum
tock=time.time()
print("Time Taken: "+str((tock-tick)*1000))
        

Time Taken: 1025.4430770874023


In [11]:
import numpy as np
import time
x=np.random.rand(100,100)
y=np.random.rand(100,100)
z=np.zeros((100,100))
tick=time.time() 
z=np.dot(x,y)
tock=time.time()
print("Time Taken: "+str((tock-tick)*1000))

Time Taken: 22.08709716796875


In [17]:
x=np.array([1,5,10,15,20])
print(np.maximum(x,10))

[10 10 10 15 20]


In [20]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
print(a)
print(b)
print(c)

[[ 0.50150001  1.79305502  0.49765232]
 [ 0.71550169  0.23517351  0.86002164]
 [-0.35442967  0.34194734  1.11723604]]
[[-0.8323164 ]
 [ 0.73694705]
 [-1.21220729]]
[[-0.41740669 -1.4923891  -0.41420419]
 [ 0.52728686  0.17331043  0.63379041]
 [ 0.42964223 -0.41451105 -1.35432167]]
